export const range = Object.freeze({     
    temps:{
        heure: {
            id: "heure",
            label: "liber.heure",
        },
        jour: {
            id: "jour",
            label: "liber.jour",
        },
    } ,
    dure:{
        rapide:{
            id:"rapide",
            label:'liber.rapide',
        },
        calme:{
            id:"calme",
            label:'liber.calme',
        },
        calme2:{
            id:"calme2",
            label:'liber.calme2',
        },
        intensif:{
            id:"intensif",
            label:'liber.intensif',
        },
    }, 
    magie:{
        
    },
    sex:{
         sex1:{
            id:"sex1",
            label:'liber.sex1',
        },
        sex2:{
            id:"sex2",
            label:'liber.sex2',
        },
        sex0:{
            id:"sex0",
            label:'liber.sex0',
        },
    } ,
    race:{
        r0:{
           label:"liber.avantrace60",
        },
        r1:{
           label:"liber.avantrace61",
        },
        r2:{
           label:"liber.avantrace62",
        },
        r3:{
           label:"liber.avantrace63",
        },
        r4:{
           label:"liber.avantrace64",
        },
        r5:{
           label:"liber.avantrace65",
        },
        r6:{
           label:"liber.avantrace10a",
        },
        r7:{
           label:"liber.avantrace66",
        },
        r8:{
           label:"liber.avantrace67",
        },
        r9:{
           label:"liber.avantrace68",
        },
        r10:{
           label:"liber.avantrace69",
        },
        r11:{
           label:"liber.avantrace70",
        },
        r12:{
           label:"liber.avantrace71",
        },
        r13:{
           label:"liber.avantrace72",
        },
        r14:{
           label:"liber.avantrace73",
        },
        r15:{
           label:"liber.avantrace74",
        },
        r16:{
           label:"liber.avantrace75",
        },
        r17:{
           label:"liber.avantrace76",
        },
        r18:{
           label:"liber.avantrace77",
        },
        r19:{
           label:"liber.avantrace77a",
        },
        r20:{
           label:"liber.avantrace77b",
        },
        r21:{
           label:"liber.avantrace92",
        },
        r22:{
           label:"liber.avantrace78",
        },
    },
    talent:{
        t0:{
           label:"liber.title58",title:"liber.title58a"
        },
        t38:{
            label:"liber.new1",title:"liber.new1a"},
        t1:{
            label:"liber.title59",title:"liber.title59a"},
        t2:{
            label:"liber.title60",title:"liber.title60a"},
        t3:{
            label:"liber.title61",title:"liber.title61a"},
        t4:{
            label:"liber.title62",title:"liber.title62a"},
        t5:{
            label:"liber.title63",title:"liber.title63a"},
        t6:{
            label:"liber.title64",title:"liber.title64a"},
        t7:{
            label:"liber.title65",title:"liber.title65a"},
        t8:{
            label:"liber.title66",title:"liber.title66a"},
        t9:{
            label:"liber.title67",title:"liber.title67a"},
        t10:{
            label:"liber.title68",title:"liber.title68a"},
        t11:{
            label:"liber.title69",title:"liber.title69a"},
        t12:{
            label:"liber.title70",title:"liber.title70a"},
        t13:{
            label:"liber.title71",title:"liber.title71a"},
        t14:{
            label:"liber.title72",title:"liber.title72a"},
        t15:{
            label:"liber.title73",title:"liber.title73a"},
        t16:{
            label:"liber.title74",title:"liber.title74a"},
        t17:{
            label:"liber.title75",title:"liber.title75a"},
        t18:{
            label:"liber.title76",title:"liber.title76a"},
        t19:{
            label:"liber.title77",title:"liber.title77a"},
        t20:{
            label:"liber.title78",title:"liber.title78a"},
        t21:{
            label:"liber.title79",title:"liber.title79a"},
        t22:{
            label:"liber.title80",title:"liber.title80a"},
        t23:{
            label:"liber.title81",title:"liber.title81a"},
        t24:{
            label:"liber.title82",title:"liber.title82a"},
        t25:{
            label:"liber.title83",title:"liber.title83a"},
        t26:{
            label:"liber.title84",title:"liber.title84a"},
        t27:{
            label:"liber.title85",title:"liber.title85a"},
        t28:{
            label:"liber.title86",title:"liber.title86a"},
        t40:{
            label:"liber.new3",title:"liber.new3a"} ,
        t29:{
            label:"liber.title87",title:"liber.title87a"},
        t30:{
            label:"liber.title88",title:"liber.title88a"},
        t31:{
            label:"liber.title89",title:"liber.title89a"},
        t32:{
            label:"liber.title90",title:"liber.title90a"},
        t33:{
            label:"liber.title91",title:"liber.title91a"},
        t34:{
            label:"liber.title92",title:"liber.title92a"},
        t35:{
            label:"liber.title93",title:"liber.title93a"},
        t36:{
            label:"liber.title94",title:"liber.title94a"},
        t37:{
            label:"liber.title95",title:"liber.title95a"},
    },
    faiblesse:{
        f32:{
            label:"liber.title114",title:"liber.title114a"},
        f0:{
            label:"liber.title96",title:"liber.title96a"},
        f21:{
            label:"liber.new6",title:"liber.new6a"},
        f1:{
            label:"liber.title97",title:"liber.title97a"},
        f19:{
            label:"liber.new4",title:"liber.new4a"},
        f22:{
            label:"liber.new7",title:"liber.new7a"},
        f23:{
            label:"liber.new8",title:"liber.new8a"},
        f2:{
            label:"liber.title98",title:"liber.title98a"},
        f3:{
            label:"liber.title99",title:"liber.title99a"},
        f19:{
            label:"liber.title115",title:"liber.title115a"},
        f4:{
            label:"liber.title00",title:"liber.title00a"},
        f5:{
            label:"liber.title01",title:"liber.title01a"},
        f24:{
            label:"liber.new9",title:"liber.new9a"},
        f25:{
            label:"liber.new10",title:"liber.new10a"},
        f20:{
            label:"liber.new5",title:"liber.new5a"},
        f6:{
            label:"liber.title02",title:"liber.title02a"},
        f7:{
            label:"liber.title03",title:"liber.title03a"},
        f8:{
            label:"liber.title04",title:"liber.title04a"},
        f26:{
            label:"liber.new11",title:"liber.new11a"},
        f9:{
            label:"liber.title05",title:"liber.title05a"},
        f10:{
            label:"liber.title06",title:"liber.title06a"},
        f11:{
            label:"liber.title07",title:"liber.title07a"},
        f28:{
            label:"liber.new13",title:"liber.new13a"},
        f12:{
            label:"liber.title08",title:"liber.title08a"},
        f29:{
            label:"liber.new14",title:"liber.new14a"},
        f13:{
            label:"liber.title09",title:"liber.title09a"},
        f14:{
            label:"liber.title110",title:"liber.title110a"},
        f30:{
            label:"liber.new15",title:"liber.new15a"},
        f15:{
            label:"liber.title111",title:"liber.title111a"},
        f31:{
            label:"liber.new16",title:"liber.new16a"},
        f27:{
            label:"liber.new12",title:"liber.new12a"},
        f17:{
            label:"liber.title113",title:"liber.title113a"},
        f16:{
            label:"liber.title112",title:"liber.title112a"}
    },
    metier:{
        m1:{
            classe:"classique",
            label:"liber.metier1",
        },
        m2:{
            classe:"classique",
            label:"liber.metier2",
        },    
        m3:{
            classe:"classique",
            label:"liber.metier3",
        },
        m4:{
            classe:"classique",
            label:"liber.metier4",
        },
        m5:{
            classe:"classique",
            label:"liber.metier5",
        },
        m6:{
            classe:"classique",
            label:"liber.metier6",
        },
        m7:{
            classe:"classique",
            label:"liber.metier7",
        },
        m8:{
            classe:"classique",
            label:"liber.metier8",
        },
        m9:{
            classe:"classique",
            label:"liber.metier9",
        },
        m10:{
            classe:"classique",
            label:"liber.metier10",
        },
        m11:{
            classe:"classique",
            label:"liber.metier11",
        },
        m12:{
            classe:"classique",
            label:"liber.metier12",
        },
        m13:{
            classe:"classique",
            label:"liber.metier13",
        },
        m14:{
            classe:"classique",
            label:"liber.metier14",
        },
        m15:{
            classe:"classique",
            label:"liber.metier15",
        },
        m16:{
            classe:"classique",
            label:"liber.metier16",
        },
        m17:{
            classe:"classique",
            label:"liber.metier17",
        },
        m18:{
            classe:"guerrier",
            label:"liber.avantrace93",
        },
        m19:{
            classe:"croiser",
            label:"liber.avantrace94",
        },
    },
    clan:{
        c1:{
            classe:"dragon",
            label:"liber.avantrace40",
        },
        c2:{
            classe:"dragon",
            label:"liber.avantrace41",
        },
        c3:{
            classe:"dragon",
            label:"liber.avantrace42",
        },
        c4:{
            classe:"dragon",
            label:"liber.avantrace43",
        },
        c5:{
            classe:"dragon",
            label:"liber.avantrace44",
        },
        c6:{
            classe:"dragon",
            label:"liber.avantrace45",
        },
        c7:{
            classe:"dragon",
            label:"liber.avantrace46",
        },
        c8:{
            classe:"dragon",
            label:"liber.avantrace47",
        },
        c9:{
            classe:"dragon",
            label:"liber.avantrace48",
        },
        c10:{
            classe:"dragon",
            label:"liber.avantrace49",
        },
        c11:{
            classe:"dragon",
            label:"liber.avantrace50",
        },
        c12:{
            classe:"dragon",
            label:"liber.avantrace51",
        },
        c13:{
            classe:"dragon",
            label:"liber.avantrace52",
        },
        c14:{
            classe:"dragon",
            label:"liber.avantrace53",
        },
        c15:{
            classe:"dragon",
            label:"liber.avantrace54",
        },
        c16:{
            classe:"dragon",
            label:"liber.avantrace55",
        },
        c17:{
            classe:"all",
            label:"liber.avantrace59",
        },
        c18:{
            classe:"all",
            label:"liber.avantrace56",
        },
        c19:{
            classe:"all",
            label:"liber.avantrace78",
        },
        c20:{
            classe:"all",
            label:"liber.avantrace79",
        },
        c21:{
            classe:"humain",
            label:"liber.avantrace57",
        },
        c22:{
            classe:"demon",
            label:"liber.avantrace39",
        },
        c23:{
            classe:"drauch",
            label:"liber.avantrace91",
        },
    },
    religion:{
        r1:{
            label:"liber.avantrace81",
            classe:"humain",
        },
        r2:{
            label:"liber.avantrace82",
            classe:"humain",
        },
        r3:{
            label:"liber.avantrace83",
            classe:"humain",
        },
        r4:{
            label:"liber.avantrace87",
            classe:"humain",
        },
        r5:{
            label:"liber.avantrace85",
            classe:"humain",
        },
        r6:{
            label:"liber.avantrace95",
            classe:"all",
        },
        r7:{
            label:"liber.avantrace80",
             classe:"all",
        },
        r8:{
            label:"liber.avantrace88",
             classe:"all",
        },
        r9:{
            label:"liber.avantrace89",
             classe:"all",
        },
        r10:{
            label:"liber.avantrace84",
             classe:"dragon",
        },
        r11:{
            label:"liber.avantrace85",
            classe:"drauch",
        },
        r12:{
            label:"liber.avantrace85",
             classe:"demon",
        },
        r13:{
            label:"liber.avantrace86",
             classe:"demon",
        },
        r14:{
            label:"liber.avantrace79",
            classe:"all",
        },
    },
});